### ISSUE TITLE
Defensive programming on env variables

### ISSUE THREAD

**Issue by JacobBrauchler** [fidildev/fettle#23]
For the env variables here: https://github.com/fidildev/fettle/blob/main/src/main/kotlin/dev/fidil/fettle/BranchProtectionCommand.kt#L9

We want to validate that the env variables were provided. If either is missing log to the user and exit execution.

**Comment by mikeylive** [comment]
Note: The env vars being used here should be moved the the main method to be verified and passed into the subcommands...not defined in the subcommand itself. @vrkljam ping me if that doesn't make sense when you get started on this.

**Comment by mikeylive** [comment]
This will turn out to be a big deal if we start making more functions (subcommands) that need GH api and the values are still in branch protections.
