### ISSUE TITLE
Run all fettle functions at once

### ISSUE THREAD

**Issue by JacobBrauchler** [fidildev/fettle#30]
Fettle functions are currently run individually. 

Add the ability to run all fettle functions with a different command. This should log a fettle grade.

- Each check has a weight of 1 and a grade is determined by dividing successful checks by the total number of checks.
- Example: Given 8 checks, a repository with 4 passing checks, the repository would receive a grade of 50% 4/8=.5.

**Comment by mikeylive** [comment]
Note: The env vars being used here should be moved the the main method to be verified and passed into the subcommands...not defined in the subcommand itself. @vrkljam ping me if that doesn't make sense when you get started on this.

**Comment by mikeylive** [comment]
This will turn out to be a big deal if we start making more functions (subcommands) that need GH api and the values are still in branch protections.

**Comment by JacobBrauchler** [comment]
@mikeylive wrong ticket
