### ISSUE TITLE
Determine distribution

### ISSUE THREAD

**Issue by tylerkron** [fidildev/fettle#41]
Do we want to distribute it with something like homebrew?

**Comment by JacobBrauchler** [comment]
https://engineering.innovid.com/distributing-command-line-tools-with-homebrew-d03e795cadc8

**Comment by JacobBrauchler** [comment]
I say lets go ahead and figure out how to distribute with homebrew for now and we can worry about anything else later.

**Comment by JacobBrauchler** [comment]
Homebrew and github-action
